source = ~/.cache/wal/colors-hyprland.conf

$mainMod = ALT
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun

exec-once = hyprpaper
exec-once = wal -R
exec-once = waypaper --restore
exec-once = waybar &
exec-once = dunst & $terminal & firefox
exec-once = /usr/lib/polkit-kde-authentication-agent-1

monitor = HDMI-A-2, preferred, 0x0, 1
monitor = eDP-1, preferred, 0x1080, 1

input {
    kb_layout = br
    kb_variant = thinkpad
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
    sensitivity = 0
}

general {
    gaps_in = 3
    gaps_out = 5
    border_size = 2
    col.active_border = $color1
    col.inactive_border = $color0
    layout = dwindle
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 8
        passes = 2
        vibrancy = 0.2
    }
    shadow {
        enabled = true
        range = 15
        render_power = 3
        color = rgba(0,0,0,0.4)
    }
}

animations {
    enabled = true
    bezier = smooth, 0.05, 0.9, 0.1, 1.0
    animation = windows, 1, 5, smooth, slide
    animation = fade, 1, 5, smooth
    animation = workspaces, 1, 6, smooth, slidevert
}

dwindle {
    pseudotile = true
    preserve_split = true
}

# Keybinds
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, D, exec, $menu
bind = $mainMod, W, exec, waypaper
bind = $mainMod, P, pseudo,
bind = $mainMod, F, fullscreen, 0

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Screenshots
bind = , Print, exec, grim ~/Pictures/screenshots/$(date +%Y-%m-%d_%H-%M-%S).png
bind = SHIFT, Print, exec, grim -g "$(slurp)" ~/Pictures/screenshots/$(date +%Y-%m-%d_%H-%M-%S).png

# Move focus
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Move windows
bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, l, movewindow, r
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, j, movewindow, d

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Scroll through workspaces
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Mouse window management
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
