$color0 = rgba({color0.strip}ff)
$color1 = rgba({color1.strip}ff)
$color2 = rgba({color2.strip}ff)
$color3 = rgba({color3.strip}ff)
$color4 = rgba({color4.strip}ff)
$color5 = rgba({color5.strip}ff)
$color6 = rgba({color6.strip}ff)
$color7 = rgba({color7.strip}ff)
$background = rgba({background.strip}ff)
$foreground = rgba({foreground.strip}ff)
